package com.MegaCityCab.admin.controller;

import com.MegaCityCab.admin.model.Add_Category;
import com.MegaCityCab.admin.dao.Add_CategoryDAO;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.*;

import java.io.IOException;
import java.util.List;

@WebServlet("/Admin/Add_CategoryServlet")
public class Add_CategoryServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Retrieve form data
        String categoryName = request.getParameter("CategoryName");
        String rate = request.getParameter("rate");
        String description = request.getParameter("description");
        String status = request.getParameter("status");

        // Create Add_Category model object
        Add_Category category = new Add_Category(0, categoryName, rate,  description, status); // id will be auto-generated by the DB

        // Save category to the database
        Add_CategoryDAO categoryDAO = new Add_CategoryDAO();
        boolean isSaved = categoryDAO.saveCategory(category);

        // Set success or error message
        if (isSaved) {
            request.setAttribute("message", "Category added successfully!");
            request.setAttribute("status", "success");
            
            Add_CategoryDAO categoryDAO1 = new Add_CategoryDAO();
            List<Add_Category> categories = categoryDAO1.getAllCategories();
            request.setAttribute("categories", categories);  // Set categories for the JSP page
            request.getRequestDispatcher("/Views/Admin/Manage_category.jsp").forward(request, response); // Forward to the JSP page
            
        } else {
            request.setAttribute("message", "Error in adding category!");
            request.setAttribute("status", "error");
        }

        
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        Add_CategoryDAO categoryDAO = new Add_CategoryDAO();
        List<Add_Category> categories = categoryDAO.getAllCategories();
        request.setAttribute("categories", categories);  // Set categories to be used in JSP
        request.getRequestDispatcher("/Views/Admin/Manage_category.jsp").forward(request, response);  // Forward to JSP
    }
}
